@deviceAddress = 192.168.3.145

### 
GET http://{{deviceAddress}}/api/definitions

###
PUT http://{{deviceAddress}}/api/definitions
Content-Type: application/json

{
  "3": {
    "name": "DHW set temperature",
    "unit": "Celsius",
    "access": "Readable",
    "interval": 30000,
    "codec": "S16",
    "converter": "10^-1"
  },
  "4": {
    "name": "HC set temperature",
    "unit": "Celsius",
    "access": "Readable",
    "interval": 30000,
    "codec": "S16",
    "converter": "10^-1"
  },
  "5": {
    "name": "set room temperature day",
    "unit": "Celsius",
    "access": "Writable",
    "interval": 30000,
    "codec": "S16",
    "converter": "10^-1"
  }
}

###
POST http://{{deviceAddress}}/api/system/reset

###
GET http://{{deviceAddress}}/api/system/status

###
GET http://{{deviceAddress}}/api/system/logs

###
GET http://{{deviceAddress}}/api/system/config
Content-Type: text/plain

###
PUT http://{{deviceAddress}}/api/system/config/can
Content-Type: text/plain

mode=Normal;

###
PUT http://{{deviceAddress}}/api/system/config/dta
Content-Type: text/plain

mode=Configured;
readOnly=false;

###
PUT http://{{deviceAddress}}/api/system/config/sep
Content-Type: text/plain

display=1;

###
GET http://{{deviceAddress}}/api/converters

###
PUT http://{{deviceAddress}}/api/converters/custom/OperatingStatus

{
  "id": 129,
  "key": "OperatingStatus",
  "description": "bitfield",
  "builtIn": false,
  "config": {
    "bitfield": {
      "key": "OperatingStatus",
      "fields": [
        "AUTO",
        "COMPR",
        "HEAT",
        "COOL",
        "DHW",
        "ELHEAT",
        "SERV",
        "PWROFF",
        "FILTER",
        "VENT",
        "HCPUMP",
        "DEFROS",
        "FILTXA",
        "FILTVA",
        "HEATUP",
        ""
      ]
    }
  }
}

###
GET http://{{deviceAddress}}/api/definitions

###
GET http://{{deviceAddress}}/api/data

###
GET http://{{deviceAddress}}/api/data/config

###
POST http://{{deviceAddress}}/api/data/config
Content-Type: application/json

[
  {"valueId": 3, "source": "SYS/0", "subscribed": true},
  {"valueId": 4, "source": "HEA/2", "subscribed": true, "writable": true},
  {"valueId": 374, "source": "SYS/0", "subscribed": true}
]

###
PUT http://{{deviceAddress}}/api/data/config/SYS/0/3
Content-Type: application/json

{"valueId": 3, "source": "SYS/0", "subscribed": true},

###
DELETE http://{{deviceAddress}}/api/data/config/SYS/0/3
