# Test device
@deviceAddress = 192.168.3.225

###
GET http://{{deviceAddress}}/api/node/status

###
GET http://{{deviceAddress}}/api/node/logs

###
GET http://{{deviceAddress}}/api/node/config/dta

###
GET http://{{deviceAddress}}/api/data

###
GET http://{{deviceAddress}}/api/devices

###
PUT http://{{deviceAddress}}/api/node/log-level/can

2


###
PUT http://{{deviceAddress}}/api/node/config/sep

display=2;

###
PUT http://{{deviceAddress}}/api/node/config/dta

mode=Configured;
readOnly=false;

###
PUT http://{{deviceAddress}}/api/node/config/can

mode=Normal;

###
PUT http://{{deviceAddress}}/api/node/config

dta.mode=Configured;
dta.readOnly=false;
sep.display=2;
can.mode=Normal;

###
GET http://{{deviceAddress}}/api/subscriptions

###
POST http://{{deviceAddress}}/api/subscriptions
Content-Type: text/plain

3,
12,
13,
14,
15@HEA/1,
18@HEA/1,
22,
274,
374,
474,
613,
833,
942,
943,
944,
945,
1431,
1433,
1435,
1436,
1467,
1611,
1684,
1690,
1691,
1696,
2330,
2331,
2332,
2333,
2334,
2335,
2336,
2337,
2340,
2341,
2344,
2345,
2346,
2347,
2348,
2349,
2350,
2351,
2352,
2353,
49391,
49396,
49397,

###
POST http://{{deviceAddress}}/api/writable
Content-Type: text/plain

17@HEA/1,
19,
1388,
1389,
1391,
1392,
1393,
1394,
1395,
1396,
1398,
1399,
1400,
1401,
1402,
1403,
1501,

###
DELETE http://{{deviceAddress}}/api/subscriptions/SYS/0/3

###
GET http://{{deviceAddress}}/api/writable

###
DELETE http://{{deviceAddress}}/api/writable/SYS/0/3

###
DELETE http://{{deviceAddress}}/api/writable/HEA/1/5

###
PUT http://{{deviceAddress}}/api/data/SYS/0/1401?accessMode=Writable
Content-Type: text/plain

21.5
