#!/bin/sh

export ARDUINO_DIRECTORIES_DATA="$REPOSITORY_BASE_PATH/.arduino"
export ARDUINO_DIRECTORIES_DOWNLOADS="$REPOSITORY_BASE_PATH/.arduino/staging"
export ARDUINO_DIRECTORIES_USER="$REPOSITORY_BASE_PATH/src"
